[theme]

# Primary accent for interactive elements
primaryColor = '#C65BCF'

# Background color for the main content area
backgroundColor = '#FFEAE3'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FFCBCB'

# Color used for almost all text
textColor = '#121481'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"